"""
Custom Tool: get_utc_now
Description: Returns the current UTC date and time in ISO 8601 format.
Generated by Willy Self-Upgrade Engine
"""

from typing import Dict, Any

TOOL_DEF = {
    "type": "function",
    "function": {
        "name": "get_utc_now",
        "description": """Returns the current UTC date and time in ISO 8601 format.""",
        "parameters": {
    "properties": {},
    "required": [],
    "type": "object"
}
    }
}

from datetime import datetime, timezone

def run(arguments: dict) -> dict:
    now = datetime.now(timezone.utc)
    return {"utc_now": now.isoformat()}
